### ISSUE TITLE
Troubleshooting animations with codesplit routes

### ISSUE THREAD

**Issue by ZakTax** [aholachek/react-flip-toolkit#47] opened 2019-01-10 17:53 UTC
I am experiencing an issue with animations not executing when codesplit routes are loaded for the first time.

I've created an MWE here that illustrates the issue: https://codesandbox.io/s/7k5yorxlz6

Compare how the site loads initially compared to what happens when you flip between routes when both nested child routes have already been loaded.

Is it possible to get react-flip-toolkit working in this situation?

**Comment by aholachek** [comment] 2019-01-10 20:12
You'd have to delay triggering the `flipKey` on the `Flipper` component until after the route lazy loaded and had rendered.  I don't know if React.lazy offers an easy way to attach a callback or otherwise be notified when the route loads?

**Comment by ZakTax** [comment] 2019-01-10 20:14
🤔 I'm confused because everything that's being animated is within Main.tsx which has already been loaded and starts on the page - it's One and Two that are being loaded on-demand. Am I missing something?

**Comment by aholachek** [comment] 2019-01-10 21:55
I think so, I'm not very knowledgable about Suspense but I think in your example when the second route is being loaded there is a flash where only the "loading..." text is visible on the page. I was able to reproduce it more clearly by downloading the sandbox locally, putting a debugger statement in react-flip-toolkit, and watching during route transitions. I saw something that looks like this for a split second on transition to the second route:

![screen shot 2019-01-10 at 4 48 00 pm](https://user-images.githubusercontent.com/3680488/50999369-ffa51f80-14f7-11e9-9e71-7f4b4f851557.png)

**Comment by ZakTax** [comment] 2019-01-10 22:01
Huh, you're right... I guess I misunderstand how suspense works (or perhaps how it's working with found router)

if you put a break on subtree modification on #root you can see the same thing:

interestingly, `Main` is still there but with `display: none` on it and that loading div is further down the tree:
![screen shot 2019-01-10 at 4 59 26 pm](https://user-images.githubusercontent.com/25751924/50999827-47787680-14f9-11e9-8034-21e89d68c0a0.png)

Thanks for the quick response, I appreciate your help. When I figure out a solution I'll post it.

**Comment by ZakTax** [comment] 2019-01-10 22:49
d'oh, my SuspenseRoute isn't working. I manually added a `Suspense` around where `Main` renders `children` and that fixes the animations not working between routes the first time you load them.

I have one more problem remaining: if you navigate directly to https://7k5yorxlz6.codesandbox.io/2 then the logo at the top isn't set up correctly - it should be a black bar but it's blank. I think I'm doing something wrong with the inverseFlip here.

**Comment by aholachek** [comment] 2019-01-12 15:14
I'm not sure, it's not blank, it's just a bit above the screen due to the `transform: translateY(-100%)` on the parent. 

I'm going to close this issue since I don't think it's related to a bug in react-flip-toolkit.

**Closed by aholachek** 2019-01-12 15:14 UTC

**Comment by ZakTax** [comment] 2019-01-12 15:16
Isn't the inverse flip id supposed to be nullifying that?

**Comment by aholachek** [comment] 2019-01-12 15:51
No, the `inverseFlipId` just cancels out transforms during animations to prevent warping.
